version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "joshgann-site"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16paao2yd9aez"
s3_prefix = "joshgann-site"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
